### ISSUE TITLE
How to use it? Working example?

### ISSUE THREAD

**Issue by geniusunil** [WarriorRocker/angular-xo-core#2]
I am very interested in using this plugin, I went through the official guides but I don't know if they include a part where i specify which wordpress site to connect with? Also in [this](https://angularxo.io/guides/angular#integrate-xorouteservice-from-angular-xo) step i get error 

> main.ts:12 TypeError: Cannot read property 'apiUrl' of undefined
>     at XoApiRoutesService.XoApiService (angular-xo.js:236)
>     at new XoApiRoutesService (angular-xo.js:390)
>     at _createClass (core.js:19831)
>     at _createProviderInstance (core.js:19801)
>     at initNgModule (core.js:19734)
>     at new NgModuleRef_ (core.js:20461)
>     at createNgModuleRef (core.js:20450)
>     at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:22281)
>     at NgModuleFactory_.push../node_modules/@angular/core/fesm5/core.js.NgModuleFactory_.create (core.js:23009)
>     at core.js:16622

Can you please provide a working code as an example?

**Comment by WarriorRocker** [comment]
Hi,

Looks like the appConfig object is not being added to your index.html.

If you are loading the Angular app through WordPress as a theme, make sure that the following settings for Xo are set:

Dist Index => '/dist/index.html' (or your specific path within the theme folder)
Redirect Mode => 'Live' (so Xo can modify the index)
App Config => true (for Xo to inject the appConfig in your index)

Note that you need an insertion point within the index.html for Xo to accurately place the appConfig object. My apologies as it looks like this may have been lost in the documentation, still trying to update all of these pages.

In short you need to add an empty script tag in your src and dist index for this. Add to your src index and build so that it also is output in your dist index.

```
<script id="xo-config" type="text/javascript"></script>
```

This is mostly due to how the Angular CLI will inject its own scripts, see the placement of this in the src index of the angularxo.io theme: https://github.com/WarriorRocker/angular-xo-material/blob/master/src/index.html

You can download and compile this theme as a full working example.

https://github.com/WarriorRocker/angular-xo-material

If you wanted to run your Angular app completely separately from WordPress you can add the appConfig object manually. Place the config output from one of the below inside a script tag in your index, or in an environment file such as: https://github.com/WarriorRocker/angular-xo-material/blob/master/src/environments/environment.local.ts

You can retrieve the current config object either:
- In your WordPress admin, Xo for Angular -> Tools -> Exports -> AppConfig Export
- Using the Xo API, for example: https://angularxo.io/xo-api/config/get

Let me know if that helps!
