### ISSUE TITLE
Unable to render index.

### ISSUE THREAD

**Issue by emmatran693** [WarriorRocker/angular-xo-core#5]
Hi sir, i have just setup wordpress on my hosting => active plugin Xo for Angular  => Active Angular Xo Material theme => Follow all in your Guide at => https://angularxo.io/guides/wordpress

My screen when i goto home page: Unable to render index.

**Comment by Jlomaka** [comment]
I got the same problem as I solved it:

1. This error indicates that in the plug-in settings in the ```Index``` tab you set the ```Live``` mod and therefore it is trying to find the file and folder ```/dist/index.html``` which you don’t have yet since you did not build the project. You don’t need to change anything now you’ll understand further.

2. You need to go to the folder of your THEME(angular-xo-material-master(i have this name)) and ```npm run-script build``` and you will have this folder, but another problem will pop up.

3. The author did not indicate that another library is needed for his library to work, which will allow you to create custom block types on the edit page, so we follow this link
 [https://wordpress.org/plugins/advanced-custom-fields/](https://wordpress.org/plugins/advanced-custom-fields/) and install and activate.

4. But that’s not all, now, after activation, the admin panel has worked too, because we forgot to put the wrapper in one file, go to ```/inc/options/theme.inc.php``` and change the code to this one
```
<? php

if (function_exists ('acf_add_options_page')) {
  add_action ('acf / init', function () {
    acf_add_options_page (array (
      'menu_title' => 'Theme Options',
      'menu_slug' => 'xo-theme-options',
      'capability' => 'edit_posts'
    ));
  }, one hundred);

  add_action ('acf / init', function () {
    acf_add_options_sub_page (array (
      'page_title' => 'Scripts',
      'menu_title' => 'Scripts',
      'menu_slug' => 'xo-theme-options-scripts',
      'parent_slug' => 'xo-theme-options',
    ));
  }, one hundred);

  add_action ('acf / init', function () {
    acf_add_options_sub_page (array (
      'page_title' => 'Footer',
      'menu_title' => 'Footer',
      'menu_slug' => 'xo-theme-options-footer',
      'parent_slug' => 'xo-theme-options',
    ));
  }, one hundred);
}
```
5. And everything will work) Here is my assembly on which everything works
```
Xo for Angular => 1.1.1

WordPress => 5.2.3

MySQL => 5.7.27-0ubuntu0.18.04.1

PHP => 7.3.9-1 + ubuntu18.04.1 + deb.sury.org + 1

Templates => 5

App Config Entrypoint => Not Found
```

**Comment by 5c0rp1** [comment]
Hi, I've got the same issue, and I tried your solution, but:
If I activate the template and the ACF, the wordpress is broke down and write out the following error message:

 "_'Theme Options', 'menu_slug' => 'xo-theme-options', 'capability' => 'edit_posts' )); }, one hundred); add_action ('acf / init', function () { acf_add_options_sub_page (array ( 'page_title' => 'Scripts', 'menu_title' => 'Scripts', 'menu_slug' => 'xo-theme-options-scripts', 'parent_slug' => 'xo-theme-options', )); }, one hundred); add_action ('acf / init', function () { acf_add_options_sub_page (array ( 'page_title' => 'Footer', 'menu_title' => 'Footer', 'menu_slug' => 'xo-theme-options-footer', 'parent_slug' => 'xo-theme-options', )); }, one hundred); }_ "

Can you help me?
